# Generated by Django 3.2.13 on 2022-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
                ('q', models.IntegerField()),
                ('a', models.IntegerField()),
                ('n', models.IntegerField()),
                ('phi', models.IntegerField()),
                ('b', models.IntegerField()),
            ],
        ),
    ]
